#!/bin/bash

SCRIPT=`realpath $0`
BASEDIR=`dirname $SCRIPT`
LOG_LOCATION=${BASEDIR}/log

if [ "$#" -ne 11 ]; then
    echo "./auction_tcp_matching_client 127.0.0.1 MARKETPORT QTYFACTOR PXFACTOR ACCOUNTID MARKETID QTY PX SIDE BUY_UPPER_BAND SELL_LOWER_BAND"
    exit 2
fi

MARKETPORT=$2
QTYFACTOR=$3
PXFACTOR=$4
ACCOUNTID=$5
MARKETID=$6
QTY=$7
PX=$8  # ARBITRARILY BIG INTEGER
SIDE=$9
BUY_UPPER_BAND=${10}   # +1%
SELL_LOWER_BAND=${11} # -1%

#MARKETPORT=34675
#QTYFACTOR=100000000
#PXFACTOR=100000000
#ACCOUNTID=9999999992
#MARKETID=2001031000000
#QTY=2000
#PX=10  # ARBITRARILY BIG INTEGER
#SIDE=BUY
#BUY_UPPER_BAND=1000000   # +1%
#SELL_LOWER_BAND=-1000000 # -1%

## ==== Pause Receiving Orders ====
#echo "Pause Receiving Orders"
#sudo kill -s SIGUSR1 `pgrep -f "pulsar_proxy.*ORDER-IN-$MARKETID"`

echo "MARKETPORT=$MARKETPORT"
echo "PXFACTOR=$PXFACTOR"
echo "QTYFACTOR=$QTYFACTOR"
echo "ACCOUNTID=$ACCOUNTID"
echo "MARKETID=$MARKETID"
echo "QTY=$QTY"
echo "PX=$PX"
echo "SIDE=$SIDE"
echo "BUY_UPPER_BAND=$BUY_UPPER_BAND"
echo "SELL_LOWER_BAND=$SELL_LOWER_BAND"

./auction_tcp_matching_client 127.0.0.1 $MARKETPORT $QTYFACTOR $PXFACTOR $ACCOUNTID $MARKETID $QTY $PX $SIDE $BUY_UPPER_BAND $SELL_LOWER_BAND >> ${LOG_LOCATION}/auction.log

#sleep 6
#
## ==== Resume Receiving Orders ====
#echo "Resume Receiving Orders"
#sudo kill -s SIGUSR1 `pgrep -f "pulsar_proxy.*ORDER-IN-$MARKETID"`
