add_library(md_tcp_service STATIC md_tcp_service.cpp implied_md_tcp_service.cpp)
target_include_directories(md_tcp_service PUBLIC ../inc)
target_include_directories(md_tcp_service PUBLIC ${CMAKE_SOURCE_DIR}/net/md_tcp_service/inc)
target_include_directories(md_tcp_service PUBLIC ${CMAKE_SOURCE_DIR}/net/tcp_service/inc)
target_include_directories(md_tcp_service PUBLIC ${CMAKE_SOURCE_DIR}/net/tcp_client/inc)
target_include_directories(md_tcp_service PUBLIC ${CMAKE_SOURCE_DIR}/matching_tcp_client/inc)
target_include_directories(md_tcp_service PUBLIC ${CMAKE_SOURCE_DIR}/md/inc)
target_include_directories(md_tcp_service PUBLIC ${CMAKE_SOURCE_DIR}/matching/order/inc)
target_include_directories(md_tcp_service PUBLIC ${CMAKE_SOURCE_DIR}/implier/inc)