add_executable(me_server me_server.cpp)
target_include_directories(me_server PUBLIC ${CMAKE_SOURCE_DIR}/coinflex_v2_common)
target_include_directories(me_server PUBLIC ${CMAKE_SOURCE_DIR}/matching_tcp_service/inc)
target_include_directories(me_server PUBLIC ${CMAKE_SOURCE_DIR}/matching/inc)
target_include_directories(me_server PUBLIC ${CMAKE_SOURCE_DIR}/matching/order/inc)
target_include_directories(me_server PUBLIC ${CMAKE_SOURCE_DIR}/net/tcp_client/inc)
target_include_directories(me_server PUBLIC ${CMAKE_SOURCE_DIR}/inc)
target_include_directories(me_server PUBLIC ${CMAKE_SOURCE_DIR}/core/inc)
target_include_directories(me_server PUBLIC ${CMAKE_SOURCE_DIR}/implier/inc)
target_include_directories(me_server PUBLIC ${CMAKE_SOURCE_DIR}/net/tcp_service/inc)
target_link_libraries(me_server matching_tcp_service tcp_service tcp_client engine pthread)
