# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CoinflexV2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Admin(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsAdmin(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Admin()
        x.Init(buf, n + offset)
        return x

    # Admin
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Admin
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

def AdminStart(builder): builder.StartObject(1)
def AdminAddVersion(builder, version): builder.PrependUint8Slot(0, version, 1)
def AdminEnd(builder): return builder.EndObject()
