# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CoinflexV2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Msg(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMsg(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Msg()
        x.Init(buf, n + offset)
        return x

    # Msg
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Msg
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    #version : Ver = VERSION;
    # Msg
    def Payload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def MsgStart(builder): builder.StartObject(2)
def MsgAddPayloadType(builder, payloadType): builder.PrependUint8Slot(0, payloadType, 0)
def MsgAddPayload(builder, payload): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)
def MsgEnd(builder): return builder.EndObject()
