# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CoinflexV2

class order_side(object):
    NONE = 0
    BUY = 1
    SELL = 2
    BUY_STOP = 3
    SELL_STOP = 4
    BUY_SELL_STOP = 5

