# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CoinflexV2

class order_time_condition(object):
    NONE = 0
    GTC = 1
    IOC = 2
    FOK = 3
    MAKER_ONLY = 4
    MAKER_ONLY_REPRICE = 5

