# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CoinflexV2

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Order(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOrder(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Order()
        x.Init(buf, n + offset)
        return x

    # Order
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Order
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 1

    # Order
    def AccountId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Order
    def MarketId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Order
    def Price(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Order
    def Quantity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Order
    def DisplayQuantity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Order
    def RemainQuantity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Order
    def LastMatchPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Order
    def LastMatchQuantity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Order
    def OrderId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Order
    def ClientOrderId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Order
    def LastMatchedOrderId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Order
    def LastMatchedOrderId2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Order
    def MatchedId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Order
    def BuyStopTriggerPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Order
    def BuyStopLimitedPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Order
    def SellStopTriggerPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Order
    def SellStopLimitedPrice(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Order
    def Side(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Order
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Order
    def TimeCondition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Order
    def OrderAction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Order
    def OrderState(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Order
    def OrderMatchedType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Order
    def TimestampEpochMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # Order
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def OrderStart(builder): builder.StartObject(26)
def OrderAddVersion(builder, version): builder.PrependUint8Slot(0, version, 1)
def OrderAddAccountId(builder, accountId): builder.PrependUint64Slot(1, accountId, 0)
def OrderAddMarketId(builder, marketId): builder.PrependUint64Slot(2, marketId, 0)
def OrderAddPrice(builder, price): builder.PrependInt64Slot(3, price, 0)
def OrderAddQuantity(builder, quantity): builder.PrependUint64Slot(4, quantity, 0)
def OrderAddDisplayQuantity(builder, displayQuantity): builder.PrependUint64Slot(5, displayQuantity, 0)
def OrderAddRemainQuantity(builder, remainQuantity): builder.PrependUint64Slot(6, remainQuantity, 0)
def OrderAddLastMatchPrice(builder, lastMatchPrice): builder.PrependInt64Slot(7, lastMatchPrice, 0)
def OrderAddLastMatchQuantity(builder, lastMatchQuantity): builder.PrependUint64Slot(8, lastMatchQuantity, 0)
def OrderAddOrderId(builder, orderId): builder.PrependUint64Slot(9, orderId, 0)
def OrderAddClientOrderId(builder, clientOrderId): builder.PrependUint64Slot(10, clientOrderId, 0)
def OrderAddLastMatchedOrderId(builder, lastMatchedOrderId): builder.PrependUint64Slot(11, lastMatchedOrderId, 0)
def OrderAddLastMatchedOrderId2(builder, lastMatchedOrderId2): builder.PrependUint64Slot(12, lastMatchedOrderId2, 0)
def OrderAddMatchedId(builder, matchedId): builder.PrependUint64Slot(13, matchedId, 0)
def OrderAddBuyStopTriggerPrice(builder, buyStopTriggerPrice): builder.PrependInt64Slot(14, buyStopTriggerPrice, 0)
def OrderAddBuyStopLimitedPrice(builder, buyStopLimitedPrice): builder.PrependInt64Slot(15, buyStopLimitedPrice, 0)
def OrderAddSellStopTriggerPrice(builder, sellStopTriggerPrice): builder.PrependInt64Slot(16, sellStopTriggerPrice, 0)
def OrderAddSellStopLimitedPrice(builder, sellStopLimitedPrice): builder.PrependInt64Slot(17, sellStopLimitedPrice, 0)
def OrderAddSide(builder, side): builder.PrependUint8Slot(18, side, 0)
def OrderAddType(builder, type): builder.PrependUint8Slot(19, type, 0)
def OrderAddTimeCondition(builder, timeCondition): builder.PrependUint8Slot(20, timeCondition, 0)
def OrderAddOrderAction(builder, orderAction): builder.PrependUint8Slot(21, orderAction, 0)
def OrderAddOrderState(builder, orderState): builder.PrependUint8Slot(22, orderState, 0)
def OrderAddOrderMatchedType(builder, orderMatchedType): builder.PrependUint8Slot(23, orderMatchedType, 0)
def OrderAddTimestampEpochMs(builder, timestampEpochMs): builder.PrependUint64Slot(24, timestampEpochMs, 0)
def OrderAddRequestId(builder, requestId): builder.PrependUint64Slot(25, requestId, 0)
def OrderEnd(builder): return builder.EndObject()
