add_library(engine engine.cpp)
target_include_directories(engine PUBLIC ${CMAKE_SOURCE_DIR}/matching/inc)
target_include_directories(engine PUBLIC ${CMAKE_SOURCE_DIR}/matching/order/inc)
target_include_directories(engine PUBLIC ${CMAKE_SOURCE_DIR}/core/inc)
target_include_directories(engine PUBLIC ${CMAKE_SOURCE_DIR}/implier/inc)