add_library(common STATIC
        aes.cpp
        base64.cpp
        cli.cpp
        connect.cpp
        dns.cpp
        ecp.cpp
        eventfd.cpp
        fd.cpp
        fp.cpp
        gzip.cpp
        hex.cpp
        hexdump.cpp
        http.cpp
        io.cpp
        json.cpp
        #linux_aio.cpp
        linux_futex.cpp
        log.cpp
        mpn.cpp
        murmur3.cpp
        #netlink.cpp
        pbkdf2.cpp
        periodic.cpp
        progress.cpp
        ripemd.cpp
        scheduler.cpp
        scrypt.cpp
        selector.cpp
        serial.cpp
        sha.cpp
        signal.cpp
        socket.cpp
        spawn.cpp
        termios.cpp
        timer.cpp
        #tls.cpp
        uri.cpp
        webclient.cpp
        websocket.cpp
        wsserver.cpp

        )
target_include_directories(common PRIVATE "${CMAKE_SOURCE_DIR}/include/" )