# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OrderBook(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOrderBook(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OrderBook()
        x.Init(buf, n + offset)
        return x

    # OrderBook
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OrderBook
    def InstrumentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # OrderBook
    def Asks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from PxLevel import PxLevel
            obj = PxLevel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderBook
    def AsksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OrderBook
    def AsksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # OrderBook
    def Bids(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from PxLevel import PxLevel
            obj = PxLevel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OrderBook
    def BidsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OrderBook
    def BidsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # OrderBook
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OrderBook
    def Checksum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # OrderBook
    def SeqNum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def OrderBookStart(builder): builder.StartObject(6)
def OrderBookAddInstrumentId(builder, instrumentId): builder.PrependUint64Slot(0, instrumentId, 0)
def OrderBookAddAsks(builder, asks): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(asks), 0)
def OrderBookStartAsksVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OrderBookAddBids(builder, bids): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(bids), 0)
def OrderBookStartBidsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OrderBookAddTimestamp(builder, timestamp): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(timestamp), 0)
def OrderBookAddChecksum(builder, checksum): builder.PrependInt64Slot(4, checksum, 0)
def OrderBookAddSeqNum(builder, seqNum): builder.PrependUint64Slot(5, seqNum, 0)
def OrderBookEnd(builder): return builder.EndObject()
