# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PxLevel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPxLevel(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PxLevel()
        x.Init(buf, n + offset)
        return x

    # PxLevel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PxLevel
    def Px(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # PxLevel
    def Qty(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PxLevel
    def NumLiqOrders(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # PxLevel
    def NumOrders(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def PxLevelStart(builder): builder.StartObject(4)
def PxLevelAddPx(builder, px): builder.PrependInt64Slot(0, px, 0)
def PxLevelAddQty(builder, qty): builder.PrependUint64Slot(1, qty, 0)
def PxLevelAddNumLiqOrders(builder, numLiqOrders): builder.PrependUint64Slot(2, numLiqOrders, 0)
def PxLevelAddNumOrders(builder, numOrders): builder.PrependUint64Slot(3, numOrders, 0)
def PxLevelEnd(builder): return builder.EndObject()
