add_executable(SampleConsumer SampleConsumer.cc)
set( CMAKE_CXX_FLAGS " -pthread" )
target_include_directories(SampleConsumer PUBLIC $ENV{HOME}/usr/local/include)
target_link_directories(SampleConsumer PUBLIC $ENV{HOME}/usr/local/lib $ENV{HOME}/usr/local/lib64)
target_link_libraries(SampleConsumer pulsarwithdeps pthread ssl crypto dl z curl protobuf-lite)
#install(TARGETS v DESTINATION ${CMAKE_INSTALL_PREFIX})

add_executable(SampleProducer SampleProducer.cc)
set( CMAKE_CXX_FLAGS " -pthread" )
target_include_directories(SampleProducer PUBLIC $ENV{HOME}/usr/local/include)
target_link_directories(SampleProducer PUBLIC $ENV{HOME}/usr/local/lib $ENV{HOME}/usr/local/lib64)
target_link_libraries(SampleProducer pulsarwithdeps pthread ssl crypto dl z curl protobuf-lite)
